### ISSUE TITLE
Wrong data format for Date in JSON

### ISSUE THREAD

**Issue by MihaelIsaev** [vapor/postgres-kit#120]
Hey guys

I have a model like

```swift
final class User: Content {
    var id: UUID?
    struct SomeData: Codable {
        var someDate: Date
    }
    var data: SomeData?
}
```

I'm saving this model without any problems, but then I can't decode it cause `someDate` saved as something like `Int`.

Changing this field type to `TimeInterval` helped, but I believe it should work with `Date` as well.
So looks like a bug 🙂

**Comment by tanner0101** [comment]
Hi @MihaelIsaev, thanks for reporting this. Could you also supply which error message you are seeing?
