### ISSUE TITLE
Memory leak while closing connections in tests

### ISSUE THREAD

**Issue by FredericRuaudel** [vapor/postgres-kit#124]
While investigating thread exhaustion in my Vapor tests (related to https://github.com/vapor/vapor/issues/1870), I've found that I've also had some issues with my PostgreSQLConnections that were not being freed correctly.

After some discussion with some NIO's expert (Cory) I found out that my problems was coming from the connection's `close()` methods I was calling in my test's teardown methods that were starting some future without waiting for their fulfilment resulting in a crash in NIO like this one:

![2019-02-20 at 09 28](https://user-images.githubusercontent.com/3808140/53083016-60177b80-34fe-11e9-86c8-7a780284724a.jpg)

The problematic code is here:

https://github.com/baarde/postgresql/blob/c9978744e6ddb2b0dc42858706c10de30c1f78ae/Sources/PostgreSQL/Connection/PostgreSQLConnection.swift#L124

```swift
    /// Closes this client.
    public func close() {
        _ = executeCloseHandlersThenClose()
    }


    /// Executes close handlers before closing.
    private  func executeCloseHandlersThenClose() -> Future<Void> {
        return channel.close(mode: .all)
    }
```

The `close()` method is discarding the `executeCloseHandlersThenClose` future result which leads to the future not being fulfilled and then leaking.

While running the memory graph debugger at the end of my tests, I've found three malloc leaked which pointed to this other part of `PostgreSQLConnection` class:

![2019-02-20 at 10 47](https://user-images.githubusercontent.com/3808140/53083355-06fc1780-34ff-11e9-865f-402dc1237bbd.jpeg)

https://github.com/baarde/postgresql/blob/c9978744e6ddb2b0dc42858706c10de30c1f78ae/Sources/PostgreSQL/Connection/PostgreSQLConnection.swift#L42

```swift
    init(queue: QueueHandler<PostgreSQLMessage, PostgreSQLMessage>, channel: Channel) {
        self.queue = queue
        self.channel = channel
        self.isClosed = false
        self.extend = [:]
        self.pipeline = channel.eventLoop.newSucceededFuture(result: ())
        channel.closeFuture.always { [weak self] in
            self?.isClosed = true
            if let current = self?.currentSend {
                current.fail(error: closeError)
            }
        }
    }
```

The discussion on discord starts here (if needed): https://discordapp.com/channels/431917998102675485/444937269808332801/547704915359956993

**Comment by FredericRuaudel** [comment]
I'm running the 1.2.2 version of PostgreSQL library

**Comment by tanner0101** [comment]
`close()` needs to not return anything to comply with the `DatabaseConnection` protocol. Maybe we can publicize [`executeCloseHandlersThenClose()`](https://github.com/vapor/postgresql/blob/1.2.2/Sources/PostgreSQL/Connection/PostgreSQLConnection.swift#L129) as an alternative way to close the connection for tests?

On master, this issue has been fixed by allowing [`close()` to return a future](https://github.com/vapor/nio-postgres/blob/master/Sources/NIOPostgres/Connection/PostgresConnection.swift#L21) and relying on the caller to close any created connections.

**Comment by terwanerik** [comment]
> Maybe we can publicize [`executeCloseHandlersThenClose()`](https://github.com/vapor/postgresql/blob/1.2.2/Sources/PostgreSQL/Connection/PostgreSQLConnection.swift#L129) as an alternative way to close the connection for tests?

Yes! Would be great as a temporary non-breaking solution.

**Comment by tanner0101** [comment]
I've opened a PR here: https://github.com/vapor/postgresql/pull/128. 

@terwanerik do you think you could test out if this fixes your problem? You can test out the code in your project by doing:

```
swift package edit PostgreSQL --revision async-close
swift package generate-xcodeproj
```

**Comment by terwanerik** [comment]
@tanner0101 I can test it out on Monday.. Not at work right now, and only have small projects on my personal laptop that don't use PostgreSQL connections in unit tests

**Comment by terwanerik** [comment]
Seems to be working! The `Fatal error: leaking promise created at` are a bit sporadic, but i'm actively developing on the project today, so if it does appear again i'll keep you posted.

**Comment by tanner0101** [comment]
This has been fixed in version 2. We now have tests to check for memory leaks going forward.
