### ISSUE TITLE
PostgresNumeric type

### ISSUE THREAD

**Issue by tanner0101** [vapor/postgres-kit#131]
The recommended way to work with `NUMERIC` columns in an existing Postgres DB is via `String`. It would be nice to have a `PostgresNumeric` type that encapsulated the numeric parsing logic as well as conversion methods to / from Decimal, Float, Double, String, etc. 

```swift
class Account: Model {
    var balance: PostgresNumeric
}

print(account.balance.lossyDouble) // Double
print(account.balance.string) // String
```

FWIW, if `Decimal` could support lossless conversion to / from `NUMERIC` (seems unlikely), we could consider using that type instead.

**Comment by tkrajacic** [comment]
Well, we should in any case make a `Decimal` in the model map to a `Numeric` on the Postgres side. For the primary use case (like amounts of money) this will always be exact. It's only insanely large magnitudes that might not be representable anymore in `Decimal` I guess.

It doesn't make much sense to use the Postgres specific type in any model because there is nothing that can be done with it (like multiplying it with a `Decimal` in Swift). The type makes only sense in the table, but never in code if there is no seamless interaction with other Swift types.

**Comment by tanner0101** [comment]
> The type makes only sense in the table, but never in code if there is no seamless interaction with other Swift types.

I would argue that making the interaction seamless hides the fact that a lossy conversion is happening which could surprise people. With what I've proposed here, it's still possible to work with the value in Swift, it's just more clear from the code that precision loss may occur. If / when someone needs to track down why precision is being lost, it will be immediately clear:

```swift
class Account: Model {
    var balance: PostgresNumeric
}

let account = try Account.find(42, on: db).wait()
account.balance.lossyDecimal += 3.14
try account.save(on: db).wait()
```

**Comment by tkrajacic** [comment]
The thing that is bugging me here is that this particular addition for example will be guaranteed not to be lossy. Like most anything we'll do with Decimals there.

But I agree on your point that hidden loss of precision is a very bad thing.

**Comment by tanner0101** [comment]
> The thing that is bugging me here is that this particular addition for example will be guaranteed not to be lossy.

Couldn't it be lossy if the current balance is within +/- 3.14 of Decimal's precision threshold?

**Comment by tkrajacic** [comment]
Maybe I'm off, but Decimal doesn't have a precision in that sense. 
Decimal stores this number as two integers: 314 and -2 which is 314 * 10 ^ -2

Any number can be represented by two Integers exactly (as long as your Integers can be arbitrarily large) using a * 10 ^ b.
First Int is all the digits you have in the number, while the second is shifting the comma b places left or right.

**Comment by calebkleveter** [comment]
@tkrajacic I wish `Decimal` stored that way, but unfortunately no. It uses this weird mantissa thing that stored 8 `UInt16` instances. Don't ask me how it works, I have no idea 😄.

**Comment by tanner0101** [comment]
Summarizing the [conversation](https://discordapp.com/channels/431917998102675485/431926916279304202/555833268180877323) from team chat:

Thanks to @tkrajacic for pointing out that `Decimal` works differently than `Double` / `Float`. It works more like 2 integers, one before and after the decimal place. With each integer's relative max/min depending on the other one. 

This means that `Decimal` is always precise within its max/min bounds. This still means that there can be lossyness when converting to / from `NUMERIC`, but it's at least less likely. Because of this, it seems appropriate to allow `Decimal` to convert to / from `NUMERIC` while also providing a lossless `PostgresNumeric` type for edge cases.

**Comment by acwright** [comment]
I hope you don't mind if I weigh back in on this discussion here. I'm the one who originally brought this up in chat.

I've been experimenting with this and I believe you can convert without loss from `NUMERIC` to `Decimal`.

Take a look at the `NumericVar` struct from numeric.c file in Postgres: https://github.com/postgres/postgres/blob/master/src/backend/utils/adt/numeric.c

```
typedef struct NumericVar
{
	int			ndigits;		/* # of digits in digits[] - can be 0! */
	int			weight;			/* weight of first digit */
	int			sign;			/* NUMERIC_POS, NUMERIC_NEG, or NUMERIC_NAN */
	int			dscale;			/* display scale */
	NumericDigit *buf;			/* start of palloc'd space for digits[] */
	NumericDigit *digits;		/* base-NBASE digits */
} NumericVar;
```

This is what is returned (as binary) in `convertFromPostgreSQLData(_ data: PostgreSQLData)`. I have had some success unwrapping this and `buf` represents the digits before the decimal and `digits` represents the digits after the decimal. It is big endian. `NumericDigit` is a char in c. digits, weight and dscale are still a mystery to me. 

But given this info from Postgres shouldn't it be possible to losslessly convert this to a Decimal?

**Comment by acwright** [comment]
Here is the extension I was using for experimentation:

```
extension Decimal: PostgreSQLDataConvertible {
    
    public static func convertFromPostgreSQLData(_ data: PostgreSQLData) throws -> Decimal {
        guard let binary = data.binary else { throw PostgreSQLError(identifier: "decimalPostgresqlDataConvertible", reason: "Could not convert from PostgreSQL data") }
        
        let byteArray: [UInt16] = binary.toArray(type: UInt16.self)
        var convertedByteArray = byteArray.map { $0.bigEndian }
        
        Swift.print(convertedByteArray)
        
        return 0
    }
    
    public func convertToPostgreSQLData() throws -> PostgreSQLData {
        return PostgreSQLData(PostgreSQLDataFormat.numeric, text: self.description)
    }
    
}
```

It is not a correct solution but if you look at the log you can see the info returned from Postgres. Take a look at the integers in the array and you can see that one is the number before the decimal and another is the number after the decimal.

**Comment by tanner0101** [comment]
@acwright `dscale` is how many significant digits are after the decimal, to get rid of trailing `0`s. You can see the current implementation [here](https://github.com/vapor/postgresql/blob/1/Sources/PostgreSQL/Data/PostgreSQLData%2BString.swift#L10-L90) that converts `NUMERIC` to `Swift.String`.

> But given this info from Postgres shouldn't it be possible to losslessly convert this to a Decimal?

No, I don't think so. You can configure `NUMERIC` to have custom precision and scale `NUMERIC(p,s)`. If do you `NUMERIC(1,1)` for example, then `1.2` would fit, but `12.34` would not. So, in this case, converting between `Swift.Decimal` and `NUMERIC` would definitely be lossy. It's obviously not likely that you would declare `NUMERIC(1,1)` in a real use case, but you can see the point that these types are not equivalent. 

Despite that, for reasons mentioned in my previous comment, I think for most uses cases converting between `Decimal` and `NUMERIC` _won't_ be lossy, and should work fine. In edge cases where it is lossy, people will be able to opt in to using `PostgresNumeric` which represents `NUMERIC` losslessly.

**Comment by tanner0101** [comment]
This has been added here https://github.com/vapor/postgres-nio/pull/23.
