### ISSUE TITLE
Allow RETURNING on update query

### ISSUE THREAD

**Issue by grahamburgsma** [vapor/postgres-kit#136]
It seems only `PostgreSQLInsert` allows `RETURNING` all at the moment. But this is also possible and useful with an `UPDATE` query.

Using with Fluent I would expect an update to return the rows it updated.
`Model.query(on: conn).update(\.someColumn, to: someValue).all()`
This would create a query like:
`UPDATE Model SET someColumn = someValue RETURNING *`

**Comment by tanner0101** [comment]
This can now be done using a custom `SQLExpression` like the following:

```swift
struct PostgresReturningID: SQLExpression {
    let base: SQLExpression
    let idKey: FieldKey

    func serialize(to serializer: inout SQLSerializer) {
        serializer.statement {
            $0.append(self.base)
            $0.append("RETURNING")
            $0.append(SQLIdentifier(self.idKey.description))
        }
    }
}
```
