### ISSUE TITLE
PostgreSQLError.stackTrace should be optional

### ISSUE THREAD

**Issue by tonyarnold** [vapor/postgres-kit#146]
https://github.com/vapor/postgres-kit/blob/561fa7905030cb1240b7359ba829fa5afbf45b00/Sources/PostgreSQL/Utilities/PostgreSQLError.swift#L28

As per the original `Core.Debuggable` protocol, this property should return an optional type:  https://github.com/vapor/core/blob/18f2436bf7a6bc2224372c0885db2e0159af1649/Sources/Debugging/Debuggable.swift#L31

I can't access the contents of this property in use, as the protocol has an extension method that returns `nil` with the correct optionality.

**Comment by tonyarnold** [comment]
Oh, I see: https://github.com/vapor/core/pull/182

Well, this sucks.

**Comment by tanner0101** [comment]
@tonyarnold the PR you referenced there was trying to change the `Debuggable` protocol to have non-optional stack trace. That would definitely break things. But I think we can fix this issue in Postgres without making any breaking changes.

**Comment by tanner0101** [comment]
Actually no, Swift isn't letting me add a deprecation. I still think we should fix this, though. See my reasoning in #147.

**Comment by tonyarnold** [comment]
I think in a future release, making the stack trace property non-optional makes sense (you can always check if it's empty, right?). Thanks for looking into this, @tanner0101 - I appreciate your time and efforts.
