### ISSUE TITLE
Add BASE type create

### ISSUE THREAD

**Issue by mattpolzin** [vapor/postgres-kit#152]
See https://www.postgresql.org/docs/9.5/sql-createtype.html

See `PostgresCreateType`.

**Comment by ahmdyasser** [comment]
Hi @mattpolzin! Where can I find `PostgresCreateType` ?

**Comment by mattpolzin** [comment]
I’m not sure actually. It’s been a long time since I worked with this library and my best guess is actually that the type I referred to in this issue does not exist anymore after a refactor at some point in the past.

**Comment by ahmdyasser** [comment]
So I think this should be closed or be edited?

**Comment by 0xTim** [comment]
Yeah I'm going to close this - feel free to reopen if it's still an issue!
