### ISSUE TITLE
Differences between macOS and Ubuntu

### ISSUE THREAD

**Issue by axtonpitt** [vapor/postgres-kit#154]
On macOS my Vapor server connected to a PostgreSQL DB works as expected, but when running it on Ubuntu (dockerfile below) the request causes a 500 error. Is there any obvious causes of this? I couldn't find anything in my searching.

Dockerfile:
```
FROM swift:4.2
WORKDIR /usr/src/app
ADD . ./
RUN swift package clean
RUN swift build -c release
RUN mkdir /usr/src/app/bin
RUN mv `swift build -c release --show-bin-path` /usr/src/app/bin

ARG port=8080
ENV PORT=$port

EXPOSE $port
ENTRYPOINT ./bin/release/Run serve -e testing -b 0.0.0.0
```

Example failure:
```
[Error] [PostgreSQL] The operation could not be completed
[ ERROR ] uncleanShutdown (ErrorMiddleware.swift:26)
[ DEBUG ] Conform `OpenSSLError` to `Debuggable` for better debug info. (ErrorMiddleware.swift:26)
```

Any help would be greatly appreciated.

**Comment by tanner0101** [comment]
@axtonpitt could you provide more information about which query is causing the `[PostgreSQL] The operation could not be completed` error?
