### ISSUE TITLE
4.0 beta 1: superEncoder is missing/fatal errors

### ISSUE THREAD

**Issue by RamblinWreck77** [vapor/postgres-kit#157]
Ran into this problem trying to save a model/content that contains child that is itself model/content. 

In PostgresDataEncoder.swift line 93, the function

```
mutating func superEncoder(forKey key: Key) -> Encoder {
      fatalError()
}
```

blows up, because (I think) in FluentKit's Model.swift line 46:

```
public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: _ModelCodingKey.self)
        try self.properties.forEach { label, property in
            let encoder = LazyEncoder { container.superEncoder(forKey: .string(label)) }
            try property.encode(to: encoder)
        }
}
```

It calls superEncoder and sure enough you hit that fatal error.

**Comment by tanner0101** [comment]
FluentKit beta.2 no longer uses `superEncoded`, so this isn't as critical. `PostgresDataEncoder/Decoder` really should implement that method properly though.
