### ISSUE TITLE
decoding array with json objects results in 'invalid JSONB data format'

### ISSUE THREAD

**Issue by leonidas-o** [vapor/postgres-kit#171]
Version: 
Vapor 3.3.3
PostgreSQL 1.5.0

I'm using a raw query to fetch all columns from User table plus all the users roles from the roles/ roles pivot table. Using this raw query directly inside the database shows me the correct values.

Raw Query
```sql
SELECT u.*, ARRAY_AGG(JSON_BUILD_OBJECT('name', r."name", 'isInternalRole', r."isInternalRole")) AS "roles"
FROM "User" u
JOIN "Role_User" ru ON u."id" = ru."userID"
JOIN "Role" r ON r."id" = ru."roleID"
GROUP BY u."id";
```
Here the roles column from my raw query. The roles column now holds an array with the two columns `name` and `isInternalRole` as json objects.
Picture1:
<img width="1301" alt="Screenshot 2020-02-17 at 11 06 58" src="https://user-images.githubusercontent.com/2997492/74643862-b355f580-5175-11ea-9c65-3fedd0bca5ee.png">

Now using this raw query with vapor
```swift
func getAllUsers() -> Future<APIUserResponse> {
        return db.withConnection{ conn in
            return conn.raw("""
            SELECT u.*, ARRAY_AGG(JSON_BUILD_OBJECT('name', r."name", 'isInternalRole', r."isInternalRole")) AS "roles"
            FROM "User" u
            JOIN "Role_User" ru ON u."id" = ru."userID"
            JOIN "Role" r ON r."id" = ru."roleID"
            GROUP BY u."id";
            """).all(decoding: UserRoleAgg.self).map{ userRoleAggCollection in
                let apiUserDataCollection = userRoleAggCollection.map{ userRoleAgg -> APIUserData in
                    let userPublic = userRoleAgg.convertToPublic()
                    let roles = userRoleAgg.roles.map{ Role(name: $0.name, isInternalRole: $0.isInternalRole) }
                    return APIUserData(user: userPublic, roles: roles)
                }
                return APIUserResponse(type: .full, source: apiUserDataCollection)
            }
        }
    }
```

The execution stops at the line `""").all(decoding: UserRoleAgg.self).map{ userRoleAggCollection in` with `NIO-ELT-#1 (2): Assertion failed: invalid JSONB data format`.
Picture2:
<img width="1532" alt="Screenshot 2020-02-16 at 22 43 59" src="https://user-images.githubusercontent.com/2997492/74641857-4d1ba380-5172-11ea-956b-2de5eb55c77c.png">

I'm using postgresql functions like `array_agg` to create the array and `json_build_object` to create the json objects inside the array. When examining `Picture 1` it seems that the format is correct.
So I guess fetching the data is working, just decoding it into `UserRoleAgg` fails.

```swift
struct UserRoleAgg: Decodable, UserDefinition {
        var id: UUID?
        var firstName: String
        ...
        var roles: [Role]
       
        func convertToPublic() -> User.Public {
            return ...
        }
}

public final class Role: Codable {
    public var id: Int?
    public var name: String
    public var isInternalRole: Bool
   
    public init(name: String, isInternalRole: Bool) {
        self.name = name
        self.isInternalRole = isInternalRole
    }
}
```
Decoding into `UserRoleAgg's` role property of type `[Role]` is causing the issue.

As a side note:
At the beginning `UserRoleAgg's` roles property was of type `[String]`, the raw query was a bit different (the first line -> `SELECT "User".*, ARRAY_REMOVE(ARRAY_AGG("Role"."name"), NULL) AS "roles" FROM "User"`). My `Role` model only had the properties `ID` and `name`. Decoding was working fine.

**Comment by MihaelIsaev** [comment]
You have to always use jsonb, e.g. `JSONB_BUILD_OBJECT `

**Comment by leonidas-o** [comment]
Oh lord, I was looking for JSONB_BUILD_OBJECT yesterday night, but couldn't find it in the postgresql docs, so I thought there is no such function. Maybe it was to late, I was to sleepy whatever. @MihaelIsaev thanks for the quick reply
