### ISSUE TITLE
Unable to connect to payed Heroku database

### ISSUE THREAD

**Issue by seeppp** [vapor/postgres-kit#186]
The `standard-0` Postgres database from Heroku requires to have ssl enabled. Therefore, when configuring the app with `.postgres(url:)` I added the `sslmode=require` to the URL.

```swift
if let urlString = Environment.get("DATABASE_URL") {
    url = URL(string: urlString + "?sslmode=require")
}
```

Now, when the vapor application tries to connect to the DB, the connection is revoked because of this: `sql_error_code = 08P01 LOG:  could not accept SSL connection: tlsv1 alert unknown ca`

In vapor 3, there was the `unverifiedTLS` transport property (https://docs.vapor.codes/3.0/deploy/heroku/#configure-the-database)

How can I achieve a valid connection to the database?

- vapor 4.5.1
- fluent-postgres-driver 2.0.0-rc.2
- postgres-kit 2.0.1
- swift 5.2.2

**Comment by 0xTim** [comment]
You can disable certificate verification when you configure the database. E.g.:

```swift
app.databases.use(.postgres(
    hostname: Environment.get("DATABASE_HOST") ?? "localhost",
    username: Environment.get("DATABASE_USERNAME") ?? "vapor_username",
    password: Environment.get("DATABASE_PASSWORD") ?? "vapor_password",
    database: Environment.get("DATABASE_NAME") ?? "vapor_database",
    tlsConfiguration: .forClient(certificateVerification: .none)
), as: .psql)
```
