### ISSUE TITLE
Column type typo?

### ISSUE THREAD

**Issue by code28** [vapor/postgres-kit#193]
I'm not sure about this, since I'm not using that case, but this looked quite odd to me and I couldn't find any documentation about it, that it might be a typo:

`case .interval: return "INTEVERAL"` in [Line 518 in PostgresColumnType.swift](https://github.com/vapor/postgres-kit/blob/master/Sources/PostgresKit/PostgresColumnType.swift#L518).

**Comment by 0xTim** [comment]
That definitely looks like a typo to me! cc @tanner0101 

@code28 I think a PR to fix would be appreciated if you're up fo fit!

**Comment by code28** [comment]
Sure!
