### ISSUE TITLE
Are transactions supported?

### ISSUE THREAD

**Issue by MoridinBG** [vapor/postgres-kit#197]
Are transactions supported? I tried a few ways to make a transaction, including raw queries, but none was successful.

**Comment by grundoon** [comment]
Hi @MoridinBG – It looks like documentation is still pending (https://github.com/vapor/docs/issues/531), though (if using `Fluent`) you can see the basic concepts of creating, nesting and testing whether you're within one in https://github.com/vapor/fluent-kit/blob/master/Sources/FluentBenchmark/Tests/TransactionTests.swift

**Comment by MoridinBG** [comment]
Hi @grundoon I am using postgres-kit directly. The fluent-kit example is just what I needed! I finally have working transactions!
The nested simpleQueries did it. I was trying to make it work with execute which didn't work.
It would be really nice if transaction support ends up in sql-kit or postgres-kit at least. Fluent can then build on top of that, while non-fluent clients can use transactions too.

**Comment by bordunosp** [comment]
U can take a connect from the pool and do whatever you want with it. 
And at the end, return back to the pool

```
let pool = EventLoopGroupConnectionPool(source: ...)

let conn = try pool.requestConnection().wait(); defer {
    pool.releaseConnection(conn)
}

do {
    _ = try conn.query("BEGIN;").wait()
    _ = try conn.query("UPDATE ...").wait()
    _ = try conn.query("UPDATE ...").wait()
    _ = try conn.query("COMMIT;").wait()
} catch let error {
    _ = try conn.query("ROLLBACK;").wait()
    throw error
}

```

**Comment by 0xTim** [comment]
Closing since transactions are supported
