### ISSUE TITLE
transaction

### ISSUE THREAD

**Issue by bordunosp** [vapor/postgres-kit#204]
Any transaction example with pool connection?

**Comment by bordunosp** [comment]
its ok?
Did I understand the approach to working with connectivity correctly?

```
let pool = ...

let conn = try! pool.requestConnection().wait(); defer {
    pool.releaseConnection(conn)
}
        
do {
    _ = try! conn.query("BEGIN;").wait()
    _ = try conn.query("UPDATE some_tbl_1 SET a = 1;").wait()
    _ = try conn.query("UPDATE some_tbl_2 SET b = 2;").wait()
    _ = try conn.query("COMMIT;").wait()
} catch let error {
    _ = try! conn.query("ROLLBACK;").wait()
    throw error
}
```

**Comment by siemensikkema** [comment]
@bordunosp I'm not sure I fully understand the question but what you wrote seems ok. Have a look at how the (higher level) fluent-postgres-driver package handles transactions: https://github.com/vapor/fluent-postgres-driver/blob/11d4fce0c5d8a027a5d131439c9c94dd3230cb8e/Sources/FluentPostgresDriver/FluentPostgresDatabase.swift#L74.
Closing this issue now but feel free to reopen.
