### ISSUE TITLE
swift 5.5 async await

### ISSUE THREAD

**Issue by bordunosp** [vapor/postgres-kit#208]
are you planning to move to the "async-await" paradigm?
mb there is already some branch for tests?

**Comment by siemensikkema** [comment]
@bordunosp we are, see for example https://github.com/vapor/fluent-kit/tree/async-await

I don't have the full overview of how much we have to adapt each repository (like postgres-kit) or if we can get by targeting the common repos like async-kit and sql-kit.

**Comment by bordunosp** [comment]
Did I understand correctly? This repository will go into oblivion and now I need to switch to the fluent-kit?

**Comment by 0xTim** [comment]
No it means that we'll focus on the higher level libraries first and then low level libraries like PostgresNIO. Every repo will eventually transition over

**Comment by bordunosp** [comment]
ок, thanks 
will w8)

**Comment by bordunosp** [comment]
not yet?

**Comment by 0xTim** [comment]
We're waiting for an Xcode release until we tag, but hopefully soon! I'm going to close the issue as this is just an ongoing issue. For any issues/features related to async APIs of Fluent, you can post in FluentKit. We have no immediate plans to add async APIs to PostgesKit but they will eventually come
