### ISSUE TITLE
URL is unable to be decoded

### ISSUE THREAD

**Issue by jtodaone** [vapor/postgres-kit#213]
### Describe the bug

At some point after 2.3.0, PostgresKit cannot decode Foundation's URL struct stored in database.

### To Reproduce

* I am using Vapor and Fluent. But I am guessing that it is reproducible on postgres-kit's own.

1. Use Vapor/Fluent and PostgresKit package 2.3.3.
2. Make a model with a URL field, and two endpoints - one for creating object, the other for fetching.
3. Send a request to create and store the object on the database.
4. Send another request to read the object.
5. See error below.

<pre>
{
    "error": true,
    "reason": "invalid field: <em>fieldname</em> type: Optional<URL> error: typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [], debugDescription: \"Expected to decode String but found a dictionary instead.\", underlyingError: nil))"
}
</pre>

### Expected behavior

An object with stored URL will be returned.

### Environment

* Vapor Framework version: 4.52.1
* Vapor Toolbox version: 18.3.3
* OS version: macOS 12.0.1

### Additional context

* Once I manually added PostgresKit 2.3.0 as dependency to my project, it started working just fine.
* Data is safely stored on the database, even on 2.3.3. The error only occurs when you try to decode it afterwards.

**Comment by m-barthelemy** [comment]
I'm hitting this issue as well with Fluent 4.6.0 and fluent-postgres-driver 2.5.0.

**Comment by m-barthelemy** [comment]
Looks like adding the following to my project fixed it, but I have no idea what I'm doing here.

```swift
import Foundation
import PostgresKit

extension URL: PostgresDecodable {
    @inlinable
    public init<JSONDecoder: PostgresJSONDecoder>(
        from buffer: inout ByteBuffer,
        type: PostgresDataType,
        format: PostgresFormat,
        context: PostgresDecodingContext<JSONDecoder>
    ) throws {
        switch (format, type) {
        case (.binary, .varchar),
             (.binary, .text),
             (.text, .text),
             (.text, .varchar):
            guard buffer.readableBytes > 0 else {
                throw PostgresDecodingError.Code.failure
            }

            guard let url = buffer.readString(length: buffer.readableBytes).flatMap({ URL(string: $0) }) else {
                throw PostgresDecodingError.Code.failure
            }
            
            self = url
        default:
            throw PostgresDecodingError.Code.typeMismatch
        }
    }
}

extension PostgresData {
    public init(url: URL) {
        var buffer = ByteBufferAllocator().buffer(capacity: url.absoluteString.lengthOfBytes(using: .utf8))
        _ = try! buffer.writeString(url.absoluteString, encoding: .utf8)
        self.init(type: .text, formatCode: .text, value: buffer)
    }
    
    public var url: URL? {
        guard var value = self.value else {
            return nil
        }
        
        switch self.formatCode {
        case .binary:
            switch self.type {
            case .varchar, .text:
                return self.string.flatMap { URL(string: $0) }
            default:
                return nil
            }
        case .text:
            return nil
        }
    }
}

@available(*, deprecated, message: "Deprecating conformance to `PostgresDataConvertible`, since it is deprecated.")
extension URL: PostgresDataConvertible {
    public static var postgresDataType: PostgresDataType {
        return .text
    }
    
    public init?(postgresData: PostgresData) {
        guard let url = postgresData.url else {
            return nil
        }
        self = url
    }

    public var postgresData: PostgresData? {
        return .init(url: self)
    }
}

```
