### ISSUE TITLE
Usage of `try!` in repository README

### ISSUE THREAD

**Issue by btech** [vapor/postgres-kit#219]
In the README for this repository you have the following code block right at the top of the [Connection Pool section](https://github.com/vapor/postgres-kit#connection-pool:)
```
let eventLoopGroup: EventLoopGroup = ...
defer { try! eventLoopGroup.syncShutdown() }

let pools = EventLoopGroupConnectionPool(
    source: PostgresConnectionSource(configuration: configuration), 
    on: eventLoopGroup
)
defer { pools.shutdown() }
```

The issue I have is that generally I've found that using a `try!` is bad practice. Is it used here because of confidence that an error wouldn't be thrown, or because if an error is thrown — at that point — it doesn't matter that it would cause a fatal error as it is the end of the program's execution anyways? And if the latter, does the absence of a successful execution of `eventLoopGroup.syncShutdown()` before termination of the program pose the possibility of unexpected behavior occurring with the underlying resource?

**Comment by 0xTim** [comment]
The main issue is that you can't throw errors inside a `defer` and you **must** ensure the `EventLoopGroup` is shutdown when you're finished with it. In the context of the README, we need to ensure any integrators shut the group down and `defer` is the perfect candidate for this in a top level environment. If you're in a position to control the lifecycle and shutdown the group in a throwing context then go for it. In the docs case as that's the end of the 'program' crashing is the best option here
