### ISSUE TITLE
allow setting "default search path"

### ISSUE THREAD

**Issue by rehatkathuria** [vapor/postgres-kit#9]
Related to #8.

**Comment by vzsg** [comment]
Not just databases, the schema name should be configurable too.

**Comment by tanner0101** [comment]
@vzsg schema name?

**Comment by vzsg** [comment]
Sorry, I was being imprecise. What I actually meant is setting a default search path after the connection is made, some database drivers expose it. The search path is important in (typ. enterprisish) scenarios where [schemas](https://www.postgresql.org/docs/9.1/static/ddl-schemas.html) are used as an extra level of grouping/access control over tables.

This has been a pretty common feature request for the libpq-based postgresql package and the -provider.

**Comment by tanner0101** [comment]
Ah okay, will re-open to track that issue then.

**Comment by tanner0101** [comment]
@fwgreen something like this:

```swift
public func boot(_ app: Application) throws {
    try app.withNewConnection(to: .psql) { conn in
        return conn.simpleQuery("SET search_path TO myschema").transform(to: ())
    }.wait()
}
```

**Comment by MrMage** [comment]
I think that would only change that setting for that single (ephemeral) connection. You could prepend it with `ALTER DATABASE xyz`, I think.

**Comment by fwgreen** [comment]
I can confirm that prepending with `ALTER DATABASE` does work!
```swift
public func boot(_ app: Application) throws {
    try app.withNewConnection(to: .psql) { conn in
        return conn.simpleQuery("ALTER DATABASE my_db SET search_path TO my_schema").transform(to: ())
    }.wait()
}
```
Maybe one day users could have something as simple as
```swift
static let entity = "my_schema.my_table"
```
But this gets us up and running, so I'll take it.  Thank you all!

**Comment by tanner0101** [comment]
Ah, didn't realize that was ephemeral to the connection. You can use `DatabasesConfig` to add connection configuration closures:

```swift
var databases = DatabasesConfig()
// register your dbs and what have you
databases.appendConfigurationHandler(on: .psql) { conn in
    return conn.simpleQuery("SET search_path TO myschema")
}
services.register(databases)
```

**Comment by fwgreen** [comment]
@tanner0101 Will this workaround continue to work in the next major release?

**Comment by BlameOmar** [comment]
This workaround is not perfect, at least not in Vapor 3. `PostgreSQLConnection` contains a `TableNameCache`, which maps OIDs <-> table names using a pair of dictionaries. Unfortunately, this isn't a 1:1 relation in the general case, and breaks whenever multiple schemas use the same table names. I wanted to create new schemas per testcase (eg. 'testing_UserTests_20190718_202247'), which would allow my tests to execute in parallel, but the corrupted `TableNameCache` cause them to not find their own tables.

I have not tried this in Vapor 4. It seems like the Postgres driver has been completely redone, so it's possible that this works now.  However, without explicit support and the tests to back it up, it's possible that this accidentally breaks even if it is currently working. I'm willing to help in this regard. Let me know what your plans are for this.
